apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kk0qileap-nodejs 
  janus-idp.io/tekton: kk0qileap-nodejs
  backstage.io/kubernetes-id: kk0qileap-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kk0qileap-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml